var projects={cards:[
    {name:"Project Aether", 
     img:"earth.JPG",
     desc:"Weather baloon website complete with real-time tracking and data collection. Now an archive website storing the collected data, images, and videos.",
     link:"https://cdogg99.github.io/aether-project-site/"},
    {name:"UT<sup>4</sup>", 
     img:"utfour.png",
     desc:"Ultimate Tic-Tac-Toe tournament creator with a working server and many smaller features.",
     link:"https://github.com/sntgC/utfour"},
    {name:"Bunn's: Burgers and Fun", 
     img:"bunns.png",
     desc:"Website for a mock family entertainment center. Allowed for users to customize and reserve their own parties.",
     link:"https://sntgc.github.io/Bunn-s/index"},
    {name:"Cookable", 
     img:"cookable.png",
     desc:"Recipe creating and sharing app. Part of the Able Suite.",
     link:"https://github.com/CDogg99/cookable"}]};